### ISSUE TITLE
Chapter support

### ISSUE THREAD

**Issue by bjoreman** [chicio/ID3TagEditor#16]
Looking through the code and docs, as far as I can tell there's no support for mp3 chapters and table of contents. Is there any particular reason for this? As a podcaster and developer of a podcasting-related app I would find this really useful. I might try to add support, but I thought I'd ask first if I'm trying something completely silly :-) …

**Comment by chicio** [comment]
Hi @bjoreman,
the only reason is that I didn't had time to add this feature 😆 . The implementation of ID3TagEditor support the most widely common tags, but I would like to more and more frame type to the id3 tag. So, I would definitely have a look at you Pull Request and generally speaking I would like to see some contributions from the community. 
At the moment I'm preparing the 3.0.0 version of ID3TagEditor but it's not finished yet. So you can add this new feature starting from master and then I will merge it into the new release (that changes a lot of things of how the id3 data is exposed to the user of the library).

Thank you for the support and remember to start my repo if you like the library.
I will wait for your pull request 😊.

Fabrizio.

**Comment by bjoreman** [comment]
Awsome, I’ll see what I can do! One of the harder parts right now was finding the spec since id3.org is so down, but I think I have enough to go by :-)

**Comment by chicio** [comment]
@bjoreman Yep, I saw that the id3.org site is gone 😆, anyway we can find the information in the web ☺️ 

PS.: remember to start the repo 🙂🙃

**Comment by bjoreman** [comment]
So I'm not missing anything (again): is there any facility right now for frames with sub-frames? Both chapters and tables of contents have sub-frames, so a nice bit of recursion would be highly suitable here :-) …

**Comment by chicio** [comment]
At the moment there's no facilities for frames and subframes. In fact I agree with you that a good data abstraction for a library like ID3TagVersion could be to expose a list of frames (and subframes) identified by an id and the specific content. In the next release 3.0.0 that I'm working on I will expose to the user that kind of data abstraction. You can see it here:

 https://github.com/chicio/ID3TagEditor/pull/13

I almost finished it but at the moment I'm not working on it because I'm busy with my main job. I hope to merge it before the summer will arrive :D.
