### ISSUE TITLE
Crashes on partial files

### ISSUE THREAD

**Issue by woko666** [chicio/ID3TagEditor#8]
**Describe the bug**
When reading partial downloads, I've identified several places where the library crashes. Mostly when making .subdata with NSMakeRange and not checking if the range is valid.

**To Reproduce**
1. Try reading e.g. first 5kB of a mp3 file (partial download)

**Expected behavior**
Not crashing

**Device (please complete the following information):**
 - Model: iPad mini, simulator

**Additional context**
I've identified the following crash points:
ID3TagParser: let frame = mp3.subdata(with: NSMakeRange(position, frameSize))
ID3FrameContentParser: let frameIdentifierData = [UInt8](frame.subdata(in: Range(0...frameIdentifierSize - 1)))
ID3FrameContentSizeParser: mp3.getBytes(&frameSize, range: NSMakeRange(frameSizePosition, 4))

**Comment by chicio** [comment]
Hi @woko666,

this is not completely unexpected. I mean: in the header of the ID3 tag is contained the size of the entire tag. So if there's a size of 200KB I expected to find frames data of that size. We can put a fix in this way: after the extraction of the size I could check if the mp3 file size is bigger the the tag size. If the mp3 file is bigger than the tag size, it means you have enough data to parse. If not, the tag is not valid and the ID3TagEditor will return nil from the `read(..)` apis. 
I will work on it after we close you pull request (Read from Data https://github.com/chicio/ID3TagEditor/pull/9).

As I told you in the pull request, remeber to support my work by starring it 😊 

Fabrizio.

**Comment by woko666** [comment]
Hi @chicio,
I'd argue that it's a bad idea to trust anything the data format tells your - the file could be corrupted, incorrectly written or just plain malicious, and we should check anything that could crash the code. 😊

As for why I'm reading partial files - I'm trying to get tags of lots of remote files, so bandwidth is a huge concern. If the file has an ID3v2 header then it makes sense to just download the first 5kB instead of up to 10s of MBs for each file. I don't really care if the rest of the header (e.g. artwork) is unavailable, as long as I can get artist, album etc., that's fine with me.

Therefore I'd suggest not returning nil, but a partial tag with data that was available before reaching EOF, as well as a flag indicating a partial file. It'd probably be too confusing for most use cases, so maybe a signature such as `public func read(from path: String, allowPartial:Bool = false) throws -> ID3Tag? {` where `allowPartial == false` returns nil as you suggested, and `allowPartial == true` returns partial match with the flag as I mentioned?

Your thoughts?

**Comment by chicio** [comment]
Hi @woko666,
I don't agree on the partial solution because the id3 standard is pretty strict. 

[http://id3.org/d3v2.3.0](http://id3.org/d3v2.3.0)

We have to assume a rigid file structure (as you can see in the ID3 doc) when you parse the mp3 and the only thing we could do is at least to check the size contained in the tag header: if the file size is less than the tag size in the header then we will throw and exception.
Your assumption to parse a part is incorrect. For example it could happen that in the first 5 KB you get a partial frame that would require a lot of if check useless, because by the ID3 standard the frame is invalid and also the tag. Consider that in the id3 tag you can find media attachment, for example in the APIC frame. In this type of frame the entire image is saved in the mp3 in binary format.

<img width="1503" alt="screen shot 2018-08-07 at 21 32 45" src="https://user-images.githubusercontent.com/4048413/43798117-dda03962-9a89-11e8-8f9d-293eac76d5a2.png">

So I would go with the check of the size of the file against the size of the tag contained in the header. If the file size is less than the tag size then I will throw an InvalidTag exception (or something similar).
I hope you will still find useful the library 😃 

Fabrizio.

**Comment by woko666** [comment]
Np, I've already made a fork to suit my needs. Just wanted to let you know about the crashes...

**Comment by chicio** [comment]
Hi @woko666,
I released a new version of the ID3TagEditor with the check on the corruption of the file discussed above. I'm closing the Issue now.
Best regards,
Fabrizio.
