### ISSUE TITLE
Delete methods missing

### ISSUE THREAD

**Issue by tcarroll2** [chicio/ID3TagEditor#90]
**Is your feature request related to a problem? Please describe.**
I'm looking for an easy method to delete frames.

**Describe the solution you'd like**
I want to have the ability to delete a frame, or modify an existing frame.  For example, some of my artwork, as mentioned in your blog post, are not set as "frontCover" but instead as "other."  I would like the ability to either change the picture type, or an easy method to delete the frame after copying the attchedPicture data and then recreate the frame with the correct type.

**Describe alternatives you've considered**
I have stepped through my code and I do not understand how to do what I am trying to achieve.

**Additional context**
None.

**Comment by chicio** [comment]
Hi @tcarroll2 , 

at the moment the easy steps in order to achieve your goal is:

* read the id3 tag and get access to the "full frame data" (search this in readme)
* remove/modify the frame you want to change
* write back the id3 tag to mp3 file

In a future release I will try to add the delete/update frame (is just a matter of composing the read/write method in order to do the steps above). I hope this can help you

Thanks,
Fabrizio.

PS remember to ⭐  start ⭐  this repo in order to support my open source work 🚀
