### ISSUE TITLE
Reading ID3 tags of large files

### ISSUE THREAD

**Issue by lordzsolt** [chicio/ID3TagEditor#98]
**Is your feature request related to a problem? Please describe.**
- Because you're using `Data(contentsOf: validPath)` inside `Mp3FileReader`, the entire file gets loaded into memory

**Describe the solution you'd like**
- According to documentation, `InputStream` is meant to be used in this case.
- https://developer.apple.com/documentation/foundation/inputstream
- Since the ID3 tags are at the start of the file, it's enough to only read `Int(tagSize) + id3TagConfiguration.headerSize()` worth
- This would involve _some_ amount of code change, to first peak into the file to get the tagSize, and then perform a second read to read the entire ID3 header

**Additional context**
- I'm writing an Audiobook player for myself, and wanted to read the ID3 tags to show some additional information, when viewing the files / playing them.
- Tested this with a 500MB audiobook, all 500 MB of it get loaded into RAM.
- Looked at the tagSize + id3TagConfiguration.headerSize() values, it would be enough to read 588549 bytes, or ~5MB

In fact, if I modify the code, and hardcode this value, it behaves exactly as before:

```swift
    func readFrom(path: String) throws -> Data {
        let validPath = URL(fileURLWithPath: path)
        guard validPath.pathExtension.caseInsensitiveCompare("mp3") == ComparisonResult.orderedSame else {
            throw ID3TagEditorError.invalidFileFormat
        }

        guard let inputStream = InputStream(fileAtPath: path) else {
            throw ID3TagEditorError.invalidFileFormat
        }

        inputStream.open()

        var buffer = [UInt8](repeating: 0, count: 588549)
        let result = inputStream.read(&buffer, maxLength: 588549)

        return Data(buffer)
}
```

----

- Have you ever thought about this problem?
- Are you interested in a contribution that would change this?
    - It would involve some slight refactor to accommodate the 2 read events.

**Comment by chicio** [comment]
Hi @lordzsolt, sorry for the late reply and thank you for your suggestion. 
This seems really interesting. At the time when I created ID3TagEditor there were no memory issue because I used it to edit simple mp3 songs (~ 10MB). Now your use case seems one where we need to work in the optimization of the library.
At the moment I'm quite busy on another side project, so I can try to implement it only in some months in the future.
But, if you wanna give it a try and open a pull request with the modification I will be more than happy to code review and help you to land the feature on the main branch.
Let me know if you want to give it a shot and try to implement it yourself or you can wait some time until I will be free and I can implement you suggestion.

**Comment by lordzsolt** [comment]
Hey @chicio, no worries. It's holiday season after all :D 

I will give it a shot implementing it myself.
I just didn't want to do it without your consent, because it's not a simple 1-2 line change.

**Comment by chicio** [comment]
@lordzsolt Thank you for your understanding 🙏 I'm more than happy to welcome new contributors on ID3TagEditor 😍. So if you want to try (given that the idea seems really good to me) don't hesitate and proceed 👍💪
